# Generated by Django 2.1.7 on 2019-02-18 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Navn på fadderbarn')),
            ],
        ),
        migrations.CreateModel(
            name='Gruppe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Navn på faddergruppe')),
                ('gender', models.CharField(choices=[('male', 'Mann'), ('female', 'Kvinne'), ('other', 'Annet/Vil ikke oppgi')], max_length=10, verbose_name='Kjønn')),
            ],
        ),
        migrations.AddField(
            model_name='barn',
            name='pri_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pri_1s', to='groupfixer.Gruppe', verbose_name='Førsteprioritet'),
        ),
        migrations.AddField(
            model_name='barn',
            name='pri_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pri_2s', to='groupfixer.Gruppe', verbose_name='Andrerioritet'),
        ),
        migrations.AddField(
            model_name='barn',
            name='pri_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pri_3s', to='groupfixer.Gruppe', verbose_name='Tredjeprioritet'),
        ),
    ]
