# Generated by Django 2.1.7 on 2019-02-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupfixer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barn',
            options={'verbose_name': 'Fadderbarn', 'verbose_name_plural': 'Fadderbarn'},
        ),
        migrations.AlterModelOptions(
            name='gruppe',
            options={'verbose_name': 'Faddergruppe', 'verbose_name_plural': 'Faddergrupper'},
        ),
        migrations.RemoveField(
            model_name='gruppe',
            name='gender',
        ),
        migrations.AddField(
            model_name='barn',
            name='gender',
            field=models.CharField(choices=[('male', 'Mann'), ('female', 'Kvinne'), ('other', 'Annet/Vil ikke oppgi')], default='male', max_length=10, verbose_name='Kjønn'),
            preserve_default=False,
        ),
    ]
