# Generated by Django 2.1.7 on 2019-02-26 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupfixer', '0002_barn_given_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barn',
            name='given_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='groupfixer.Gruppe', verbose_name='Tildelt gruppe'),
        ),
    ]
