# Generated by Django 3.1.12 on 2022-08-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupfixer', '0003_auto_20190226_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barn',
            options={'ordering': ['name'], 'verbose_name': 'Fadderbarn', 'verbose_name_plural': 'Fadderbarn'},
        ),
    ]
