# Generated by Django 3.1.14 on 2025-08-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupfixer', '0004_auto_20220816_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruppe',
            name='is_non_alcoholic',
            field=models.BooleanField(default=False, verbose_name='Faddergruppen er alkoholfri'),
        ),
    ]
