# Generated by Django 3.1.14 on 2025-08-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupfixer', '0005_gruppe_is_non_alcoholic'),
    ]

    operations = [
        migrations.AddField(
            model_name='barn',
            name='wants_nonalcoholic',
            field=models.BooleanField(default=False, verbose_name='Fadderbarnet ønsker kun akoholfri faddergruppe'),
        ),
    ]
