# Generated by Django 3.1.14 on 2026-04-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupfixer', '0006_barn_wants_nonalcoholic'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruppe',
            name='max_size',
            field=models.IntegerField(default=20, verbose_name='Maksimal størrelse på faddergruppe'),
        ),
        migrations.AddField(
            model_name='gruppe',
            name='min_size',
            field=models.IntegerField(default=10, verbose_name='Minimal størrelse på faddergruppe'),
        ),
    ]
