DEFAULT_USE_STANDARD_GROUP_SIZE = False
DEFAULT_MINIMUM_SIZE = 10
DEFAULT_MAXIMUM_SIZE = 20
DEFAULT_MINIMUM_FEMALE_PROPORTION = 0.35
DEFAULT_MAXIMUM_FEMALE_PROPORTION = 0.65
DEFAULT_RESPECT_NONALCOHOLIC = True

FIRST_PRI_REWARD = 10
SECOND_PRI_REWARD = 8
THIRD_PRI_REWARD = 5